### ISSUE TITLE
[Bug]: pest()->extend() as a default value not working in Pest3 (legacy uses() do that well)

### ISSUE THREAD

**Issue by julien-boudry** [pestphp/pest#1224]
### What Happened

pest()->extend() api is not really equivalents to the uses() API. Default value does not work anymore.

```shell
Test case `Tests\AlgoTestCase` can not be used. The folder `/Users/julien/Code/Condorcet/tests/src/Algo/Methods/Borda/BordaCountTest.php` already uses the test case `Tests\CondorcetTestCase`

Location: /Users/julien/Code/Condorcet/vendor/pestphp/pest/src/Repositories/TestRepository.php:181

#0 /Users/julien/Code/Condorcet/vendor/pestphp/pest/src/Repositories/TestRepository.php(163): Pest\Repositories\TestRepository->make(Object(Pest\Factories\TestCaseFactory))
#1 /Users/julien/Code/Condorcet/vendor/pestphp/pest/overrides/Runner/TestSuiteLoader.php(97): Pest\Repositories\TestRepository->makeIfNeeded('/Users/julien/C...')
#2 /Users/julien/Code/Condorcet/vendor/pestphp/pest/overrides/Runner/TestSuiteLoader.php(98): PHPUnit\Runner\TestSuiteLoader::PHPUnit\Runner\{closure}()
#3 /Users/julien/Code/Condorcet/vendor/phpunit/phpunit/src/Framework/TestSuite.php(247): PHPUnit\Runner\TestSuiteLoader->load('/Users/julien/C...')
#4 /Users/julien/Code/Condorcet/vendor/phpunit/phpunit/src/TextUI/Configuration/Xml/TestSuiteMapper.php(105): PHPUnit\Framework\TestSuite->addTestFile('/Users/julien/C...', Array)
#5 /Users/julien/Code/Condorcet/vendor/phpunit/phpunit/src/TextUI/Configuration/TestSuiteBuilder.php(75): PHPUnit\TextUI\XmlConfiguration\TestSuiteMapper->map('/Users/julien/C...', Object(PHPUnit\TextUI\Configuration\TestSuiteCollection), '', '')
#6 /Users/julien/Code/Condorcet/vendor/phpunit/phpunit/src/TextUI/Application.php(407): PHPUnit\TextUI\Configuration\TestSuiteBuilder->build(Object(PHPUnit\TextUI\Configuration\Configuration))
```

### How to Reproduce

![image](https://github.com/user-attachments/assets/e5c1c13a-04b3-4e9e-a3a6-577243fc8e38)

### Sample Repository

https://github.com/julien-boudry/Condorcet

### Pest Version

3.0

### PHP Version

8.3.10

### Operation System

macOS

**Comment by nunomaduro** [comment]
Can you remove `pest()->extend(Tests\CondorcetTestCase::class);` and try again?

**Comment by julien-boudry** [comment]
Yes, it's working if I remove `pest()->extend(Tests\CondorcetTestCase::class);`

But the behavior is different. I want all tests to use CondorcetTestCase::class by default.

**Comment by nunomaduro** [comment]
we didn't support `uses(CondorcetTestCase::class)` call without an `->in()` method on Pest 2; so that call was doing nothing.
