### ISSUE TITLE
BindingResolutionException when trying to generate coverage

### ISSUE THREAD

**Issue by genesiscz** [pestphp/pest#271]
PHP 8.0
Pest v1.0.2

Command:
`./vendor/bin/pest --coverage`

Response: 

```
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /project/vendor/laravel/framework/src/Illuminate/Container/Container.php:1038
Stack trace:
#0 /project/vendor/laravel/framework/src/Illuminate/Container/Container.php(839): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /project/vendor/laravel/framework/src/Illuminate/Container/Container.php(712): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(826): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array, true)
#3 /project/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Foundation\Application->resolve('Illuminate\\Cont...', Array)
#4 /project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(811): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#5 /project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(164): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#6 /project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#7 /project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(94): Illuminate\Foundation\Bootstrap\HandleExceptions->renderForConsole(Object(Illuminate\Contracts\Container\BindingResolutionException))
#8 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Illuminate\Contracts\Container\BindingResolutionException))
#9 {main}
thrown in /project/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 1038

Fatal error: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /project/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 1038

Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /project/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 1038

Call Stack:
59.5769   56570224   1. Illuminate\Foundation\Bootstrap\HandleExceptions->handleException($e = class Pest\Exceptions\ShouldNotHappen { protected $message = '\nThis should not happen - please create an new issue here: https://github.com/pestphp/pest.\n\n- Issue: Coverage not found in path: /project/vendor/pestphp/.temp/coverage.php.\n- PHP version: 8.0.2\n- Operating system: Darwin'; private ${Exception}string = ''; protected $code = 1; protected $file = '/project/vendor/pestphp/pest/src/Exceptions/ShouldNotHappen.php'; protected $line = 38; private array ${Exception}trace = [0 => [...], 1 => [...], 2 => [...], 3 => [...], 4 => [...]]; private ?Throwable ${Exception}previous = class Exception { protected $message = 'Coverage not found in path: /project/vendor/pestphp/.temp/coverage.php.'; private $string = ''; protected $code = 0; protected $file = '/project/vendor/pestphp/pest/src/Exceptions/ShouldNotHappen.php'; protected $line = 38; private array $trace = [...]; private ?Throwable $previous = NULL }; public $xdebug_message = '\nPest\\Exceptions\\ShouldNotHappen: \nThis should not happen - please create an new issue here: https://github.com/pestphp/pest.\n\n- Issue: Coverage not found in path: /project/vendor/pestphp/.temp/coverage.php.\n- PHP version: 8.0.2\n- Operating system: Darwin in /project/vendor/pestphp/pest/src/Exceptions/ShouldNotHappen.php on line 38\n\nCall Stack:\n    0.0009     401552   1. {main}() /project/vendor/pestphp/pest/bin/pest:0\' }) /project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:0
59.5778   56571208   2. Illuminate\Foundation\Bootstrap\HandleExceptions->renderForConsole($e = class Illuminate\Contracts\Container\BindingResolutionException { protected $message = 'Target [Illuminate\\Contracts\\Debug\\ExceptionHandler] is not instantiable.'; private ${Exception}string = ''; protected $code = 0; protected $file = '/project/vendor/laravel/framework/src/Illuminate/Container/Container.php'; protected $line = 1038; private array ${Exception}trace = [0 => [...], 1 => [...], 2 => [...], 3 => [...], 4 => [...], 5 => [...], 6 => [...], 7 => [...]]; private ?Throwable ${Exception}previous = NULL; public $xdebug_message = '\nIlluminate\\Contracts\\Container\\BindingResolutionException: Target [Illuminate\\Contracts\\Debug\\ExceptionHandler] is not instantiable. in /project/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 1038\n\nCall Stack:\n   59.5769   56570224   1. Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException($e = class Pest\\Exceptions\\ShouldNotHappen { protected $message = \'\\nThis should not happen - please create an new issue here: https://githu' }) /project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:94
59.5778   56571208   3. Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler() /project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:108
59.5778   56571208   4. Illuminate\Foundation\Application->make($abstract = 'Illuminate\\Contracts\\Debug\\ExceptionHandler', $parameters = ???) /project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:164
59.5778   56571208   5. Illuminate\Foundation\Application->make($abstract = 'Illuminate\\Contracts\\Debug\\ExceptionHandler', $parameters = []) /project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:811
59.5778   56571208   6. Illuminate\Foundation\Application->resolve($abstract = 'Illuminate\\Contracts\\Debug\\ExceptionHandler', $parameters = [], $raiseEvents = ???) /project/vendor/laravel/framework/src/Illuminate/Container/Container.php:651
59.5778   56571208   7. Illuminate\Foundation\Application->resolve($abstract = 'Illuminate\\Contracts\\Debug\\ExceptionHandler', $parameters = [], $raiseEvents = TRUE) /project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:826
59.5778   56571208   8. Illuminate\Foundation\Application->build($concrete = 'Illuminate\\Contracts\\Debug\\ExceptionHandler') /project/vendor/laravel/framework/src/Illuminate/Container/Container.php:712
59.5778   56571304   9. Illuminate\Foundation\Application->notInstantiable($concrete = 'Illuminate\\Contracts\\Debug\\ExceptionHandler') /project/vendor/laravel/framework/src/Illuminate/Container/Container.php:839


Whoops\Exception\ErrorException

Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /project/vendor/laravel/framework/src/Illuminate/Container/Container.php:1038
Stack trace:
#0 /project/vendor/laravel/framework/src/Illuminate/Container/Container.php(839): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /project/vendor/laravel/framework/src/Illuminate/Container/Container.php(712): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(826): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array, true)
#3 /project/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Foundation\Application->resolve('Illuminate\\Cont...', Array)
#4 /project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(811): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#5 /project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(164): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#6 /project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#7 /project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(94): Illuminate\Foundation\Bootstrap\HandleExceptions->renderForConsole(Object(Illuminate\Contracts\Container\BindingResolutionException))
#8 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Illuminate\Contracts\Container\BindingResolutionException))
#9 {main}
thrown

at vendor/laravel/framework/src/Illuminate/Container/Container.php:1038
1034▕         } else {
1035▕             $message = "Target [$concrete] is not instantiable.";
1036▕         }
1037▕
➜ 1038▕         throw new BindingResolutionException($message);
1039▕     }
1040▕
1041▕     /**
1042▕      * Throw an exception for an unresolvable primitive.

+1 vendor frames
2   [internal]:0
Whoops\Run::handleShutdown()
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /project/vendor/laravel/framework/src/Illuminate/Container/Container.php:1038
Stack trace:
#0 /project/vendor/laravel/framework/src/Illuminate/Container/Container.php(839): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /project/vendor/laravel/framework/src/Illuminate/Container/Container.php(712): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(826): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array, true)
#3 /project/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Foundation\Application->resolve('Illuminate\\Cont...', Array)
#4 /project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(811): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#5 /project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(164): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#6 /project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#7 /project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(94): Illuminate\Foundation\Bootstrap\HandleExceptions->renderForConsole(Object(Illuminate\Contracts\Container\BindingResolutionException))
#8 /project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(130): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Illuminate\Contracts\Container\BindingResolutionException))
#9 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#10 {main}
thrown in /project/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 1038

Fatal error: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /project/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 1038

Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /project/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 1038

Call Stack:
59.6702   56613144   1. Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown() /project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:0
59.6715   56630560   2. Illuminate\Foundation\Bootstrap\HandleExceptions->handleException($e = class Symfony\Component\ErrorHandler\Error\FatalError { private $error = ['type' => 1, 'message' => 'Uncaught Illuminate\\Contracts\\Container\\BindingResolutionException: Target [Illuminate\\Contracts\\Debug\\ExceptionHandler] is not instantiable. in /project/vendor/laravel/framework/src/Illuminate/Container/Container.php:1038\nStack trace:\n#0 /project/vendor/laravel/framework/src/Illuminate/Container/Container.php(839): Illuminate\\Container\\Container->notInstantiable(\'Illuminate\\\\Cont...\')\n#1 /project/vendor/laravel/fra', 'file' => '/project/vendor/laravel/framework/src/Illuminate/Container/Container.php', 'line' => 1038]; protected $message = 'Uncaught Illuminate\\Contracts\\Container\\BindingResolutionException: Target [Illuminate\\Contracts\\Debug\\ExceptionHandler] is not instantiable. in /project/vendor/laravel/framework/src/Illuminate/Container/Container.php:1038\nStack trace:\n#0 /project/vendor/laravel/framework/src/Illuminate/Container/Container.php(839): Illuminate\\Container\\Container->notInstantiable(\'Illuminate\\\\Cont...\')\n#1 /project/vendor/laravel/fra'; private ${Error}string = ''; protected $code = 0; protected $file = '/project/vendor/laravel/framework/src/Illuminate/Container/Container.php'; protected $line = 1038; private array ${Error}trace = [0 => [...], 1 => [...], 2 => [...]]; private ?Throwable ${Error}previous = NULL }) /project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:130
59.6715   56642616   3. Illuminate\Foundation\Bootstrap\HandleExceptions->renderForConsole($e = class Illuminate\Contracts\Container\BindingResolutionException { protected $message = 'Target [Illuminate\\Contracts\\Debug\\ExceptionHandler] is not instantiable.'; private ${Exception}string = ''; protected $code = 0; protected $file = '/project/vendor/laravel/framework/src/Illuminate/Container/Container.php'; protected $line = 1038; private array ${Exception}trace = [0 => [...], 1 => [...], 2 => [...], 3 => [...], 4 => [...], 5 => [...], 6 => [...], 7 => [...], 8 => [...]]; private ?Throwable ${Exception}previous = NULL; public $xdebug_message = '\nIlluminate\\Contracts\\Container\\BindingResolutionException: Target [Illuminate\\Contracts\\Debug\\ExceptionHandler] is not instantiable. in /project/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 1038\n\nCall Stack:\n   59.6702   56613144   1. Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown() /project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:0\n   59.6715   56630560  ' }) /project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:94
59.6715   56642616   4. Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler() /project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:108
59.6715   56642616   5. Illuminate\Foundation\Application->make($abstract = 'Illuminate\\Contracts\\Debug\\ExceptionHandler', $parameters = ???) /project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:164
59.6715   56642616   6. Illuminate\Foundation\Application->make($abstract = 'Illuminate\\Contracts\\Debug\\ExceptionHandler', $parameters = []) /project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:811
59.6715   56642616   7. Illuminate\Foundation\Application->resolve($abstract = 'Illuminate\\Contracts\\Debug\\ExceptionHandler', $parameters = [], $raiseEvents = ???) /project/vendor/laravel/framework/src/Illuminate/Container/Container.php:651
59.6715   56642616   8. Illuminate\Foundation\Application->resolve($abstract = 'Illuminate\\Contracts\\Debug\\ExceptionHandler', $parameters = [], $raiseEvents = TRUE) /project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:826
59.6715   56642616   9. Illuminate\Foundation\Application->build($concrete = 'Illuminate\\Contracts\\Debug\\ExceptionHandler') /project/vendor/laravel/framework/src/Illuminate/Container/Container.php:712
59.6715   56642712  10. Illuminate\Foundation\Application->notInstantiable($concrete = 'Illuminate\\Contracts\\Debug\\ExceptionHandler') /Users/Martin/Dropbox/_php/Speeder/vendor/laravel/framework/src/Illuminate/Container/Container.php:839
```

**Comment by nunomaduro** [comment]
What coverage driver are you using?

**Comment by genesiscz** [comment]
xDebug, but I have pcov installed too. Not sure which one it does choose.

**Comment by danilopolani** [comment]
+1 here. I recently updated to XDebug 3 with this config:

```
[xdebug]
zend_extension = xdebug.so
xdebug.mode = develop
xdebug.start_with_request = trigger
xdebug.output_dir=/var/tmp
xdebug.var_display_max_depth = 10
```

Whenever I run the test suite with code coverage the following the same error is being thrown. Note that the suite runs successfully but it's unable to generate the coverage.

**Comment by danilopolani** [comment]
After downgrading to XDebug 2.x with `pecl install xdebug-2.9.8` I can confirm that the issue happens only with XDebug 3. To me it's not a big issue to use XDebug 2, but it's weird (cc @nunomaduro )

**Comment by owenvoke** [comment]
@danilopolani, it looks like in your config Coverage isn't enabled. You need to specify it as part of the mode for Xdebug 3 otherwise the driver won't be picked up.

```ini
xdebug.mode = develop,coverage
```

**Comment by nunomaduro** [comment]
@danilopolani @owenvoke Can we know if that mode is activated on the PHP runtime?

**Comment by danilopolani** [comment]
> @danilopolani @owenvoke Can we know if that mode is activated on the PHP runtime?

Tomorrow I'm gonna try and let you know!

**Comment by owenvoke** [comment]
It's the `php-code-coverage` package that detects it. So I guess. 👍🏻

https://github.com/sebastianbergmann/php-code-coverage

I think we should probably check in the [`pestphp/pest-plugin-coverage`](https://github.com/pestphp/pest-plugin-coverage) with `Coverage::isAvailable()` in the `handlesArguments()` method, and output an error there instead of in the output... But I'm not entirely sure.

**Comment by danilopolani** [comment]
Adding the `coverage` mode too to XDebug 3 solves this issue to me!

**Comment by ngarawakimani** [comment]
Thank you so much @danilopolani

**Comment by genesiscz** [comment]
@nunomaduro how is this fixed? shouldn't you at least provide this in documentation, or throw an error instead of a non-sense error I am getting?

**Comment by nunomaduro** [comment]
@genesiscz Can you make a contribution to the docs / or to the source coding adding a helpful error?
