### ISSUE TITLE
Laravel Autoload require_once Console.php error

### ISSUE THREAD

**Issue by naikshy** [pestphp/pest#519]
PHP 8.0.14
Laravel Framework 8.80.0

### How it started
After ran 
`composer require pestphp/pest-plugin-laravel --dev`

got error
```
Fatal error: Uncaught Error: Class "Artisan" not found in /var/www/app/Console.php:16
Stack trace:
#0 /var/www/app/vendor/pestphp/pest-plugin-laravel/src/Autoload.php(18): require_once()
#1 /var/www/app/vendor/pestphp/pest-plugin-laravel/src/Autoload.php(20): {closure}()
#2 /var/www/app/vendor/composer/autoload_real.php(78): require('/var/www/app/ve...')
```
### Why
`pest-plugin-laravel/src/Autoload.php` trying to load  `console.php` in the laravel root directory, instead of `/vendor/pestphp/pest-plugin-laravel/src/Console.php`
```
pest-plugin-laravel/src/Autoload.php

<?php

(static function () {
    $files = [
        'Authentication.php',
        'Console.php',
        'Container.php',
        'Database.php',
        'ExceptionHandling.php',
        'Expectations.php',
        'Http.php',
        'MocksApplicationServices.php',
        'Session.php',
        'Time.php',
    ];

    foreach ($files as $file) {
        require_once $file;
    }
})(); 
```
### How to fix
Use more specific file path
```
    foreach ($files as $file) {
        require_once dirname(__FILE__).DIRECTORY_SEPARATOR.$file;
    }
```
instead of
```
    foreach ($files as $file) {
        require_once $file;
    }
```

**Comment by owenvoke** [comment]
Interesting, sounds like a good idea. Do you want to open a PR? 👍🏻

---

On another note, you can do:
```diff
- dirname(__FILE__).DIRECTORY_SEPARATOR.$file;
+ __DIR__."/{$file}";
```
The `/` directory separator works on all OSs, and is converted to backslash on Windows. And `__DIR__` is the equivalent of `dirname(__FILE__)` 👍🏻

**Comment by naikshy** [comment]
Thanks for the note)
yeah, I'll create the PR
