### ISSUE TITLE
PHP Fatal error:  Uncaught ReflectionException: Class cache.store does not exist

### ISSUE THREAD

**Issue by diegonella** [pestphp/pest#558]
I have installed pest with laravel plugin, after installing it in my project with the following commands

```
$ composer require pestphp/pest-plugin-laravel --dev
$ php artisan pest:install
$ ./vendor/bin/pest --init

./vendor/bin/pest

Output
Tests\ExampleTest
Tests: 1 passed
Time: 0.02s
```

But when I run
php artisan route:list or php artisan tinker

It just doesn't do anything.

In php-pfm.log
```
[24-Aug-2022 08:23:41 America/Argentina/Buenos_Aires] PHP Fatal error:  Uncaught ReflectionException: Class cache.store does not exist in /Users/diego/valet_sites/bm3/vendor/laravel/framework/src/Illuminate/Container/Container.php:877
Stack trace:
#0 /Users/diego/valet_sites/bm3/vendor/laravel/framework/src/Illuminate/Container/Container.php(877): ReflectionClass->__construct('cache.store')
#1 /Users/diego/valet_sites/bm3/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\Container\Container->build('cache.store')
#2 /Users/diego/valet_sites/bm3/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): Illuminate\Container\Container->resolve('cache.store', Array, true)
#3 /Users/diego/valet_sites/bm3/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\Foundation\Application->resolve('cache.store', Array)
#4 /Users/diego/valet_sites/bm3/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(836): Illuminate\Container\Container->make('cache.store', Array)
#5 /Users/diego/valet_sites/bm3/vendor/lara in /Users/diego/valet_sites/bm3/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 879

```

I'm using
PHP 7.4.29
Laravel 8.83.13

Any idea where the problem could come from?

**Comment by fabio-ivona** [comment]
Hi @diegonella could you share a simple repository with a reproduction of this issue?

I can't see any reference to Pest in your stacktrace

**Comment by diegonella** [comment]
> Hi @diegonella could you share a simple repository with a reproduction of this issue?
> 
> I can't see any reference to Pest in your stacktrace

Hello, sorry for the delay, I was with c0v1d, luckily I'm better now.
I am going to prepare a repository and I am going to share it with you, since it is a private repository.
I will be sending you the invitation during the day.
