### ISSUE TITLE
Unexpected and downright weird "Route not found" error

### ISSUE THREAD

**Issue by neoighodaro** [pestphp/pest#589]
Hey,

Not sure what I could be doing wrong but I have a route that accepts a post request:

It should fail with user is not logged in (i use Jetstream)... When I run the test once it passes, but running the same exact test again in the same file returns a "Route 'login' not found". Any one have any idea why this could be? It only happens when theres some sort of redirect on the previous tests routes.

It also happens when i try to test redirecting to email verification when the user is not verified.

https://user-images.githubusercontent.com/807318/192138055-71d0ad05-a419-4bb5-964e-3a873401e9a0.mov

```<?php

declare(strict_types=1);

uses()->group('boosts', 'boosts:store');

it('will return unauthorized when not logged in')
    ->post('/boosts')
    ->assertRedirectContains('login');

it('will return unauthorized when not logged in again')
    ->post('/boosts')
    ->assertRedirectContains('login'); // This fails
```

```~/Dev/boosts v0.x*
❯ php artisan test --group=boosts:store

   FAIL  Tests\Feature\Boost\StoreBoostTest
  ✓ it will return unauthorized when not logged in
  ⨯ it will return unauthorized when not logged in again

  ---

  • Tests\Feature\Boost\StoreBoostTest > it will return unauthorized when not logged in again
  Expected response status code [201, 301, 302, 303, 307, 308] but received 500.
  Failed asserting that false is true.
  
  The following exception occurred during the last request:
  
  Symfony\Component\Routing\Exception\RouteNotFoundException: Route [login] not defined. in /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:467
  Stack trace:
  #0 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(760): Illuminate\Routing\UrlGenerator->route('login', Array, true)
  #1 /Users/neo/Dev/boosts/app/Http/Middleware/Authenticate.php(31): route('login')
  #2 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(83): App\Http\Middleware\Authenticate->redirectTo(Object(Illuminate\Http\Request))
  #3 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(68): Illuminate\Auth\Middleware\Authenticate->unauthenticated(Object(Illuminate\Http\Request), Array)
  #4 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(42): Illuminate\Auth\Middleware\Authenticate->authenticate(Object(Illuminate\Http\Request), Array)
  #5 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'sanctum')
  #6 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #7 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
  #8 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #9 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
  #10 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #11 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
  #12 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
  #13 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #14 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
  #15 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #16 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
  #17 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #18 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
  #19 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
  #20 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
  #21 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
  #22 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(189): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
  #23 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
  #24 /Users/neo/Dev/boosts/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #25 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
  #26 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #27 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
  #28 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle(Object(Illuminate\Http\Request), Object(Closure))
  #29 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #30 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
  #31 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings->handle(Object(Illuminate\Http\Request), Object(Closure))
  #32 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #33 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
  #34 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #35 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
  #36 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #37 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
  #38 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #39 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
  #40 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #41 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(164): Illuminate\Pipeline\Pipeline->then(Object(Closure))
  #42 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(133): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
  #43 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(545): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
  #44 /Users/neo/Dev/boosts/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(340): Illuminate\Foundation\Testing\TestCase->call('POST', '/boosts', Array, Array, Array, Array)
  #45 [internal function]: Illuminate\Foundation\Testing\TestCase->post('/boosts')
  #46 /Users/neo/Dev/boosts/vendor/pestphp/pest/src/Support/Reflection.php(38): ReflectionMethod->invoke(Object(P\Tests\Feature\Boost\StoreBoostTest), '/boosts')
  #47 /Users/neo/Dev/boosts/vendor/pestphp/pest/src/Support/HigherOrderMessage.php(93): Pest\Support\Reflection::call(Object(P\Tests\Feature\Boost\StoreBoostTest), 'post', Array)
  #48 /Users/neo/Dev/boosts/vendor/pestphp/pest/src/Support/HigherOrderMessageCollection.php(43): Pest\Support\HigherOrderMessage->call(Object(P\Tests\Feature\Boost\StoreBoostTest))
  #49 /Users/neo/Dev/boosts/vendor/pestphp/pest/src/Factories/TestCaseFactory.php(148): Pest\Support\HigherOrderMessageCollection->chain(Object(P\Tests\Feature\Boost\StoreBoostTest))
  #50 [internal function]: P\Tests\Feature\Boost\StoreBoostTest->Pest\Factories\{closure}()
  #51 /Users/neo/Dev/boosts/vendor/pestphp/pest/src/Concerns/Testable.php(299): call_user_func_array(Object(Closure), Array)
  #52 /Users/neo/Dev/boosts/vendor/pestphp/pest/src/Support/ExceptionTrace.php(29): P\Tests\Feature\Boost\StoreBoostTest->Pest\Concerns\{closure}()
  #53 /Users/neo/Dev/boosts/vendor/pestphp/pest/src/Concerns/Testable.php(300): Pest\Support\ExceptionTrace::ensure(Object(Closure))
  #54 /Users/neo/Dev/boosts/vendor/pestphp/pest/src/Concerns/Testable.php(276): P\Tests\Feature\Boost\StoreBoostTest->__callClosure(Object(Closure), Array)
  #55 /Users/neo/Dev/boosts/vendor/phpunit/phpunit/src/Framework/TestCase.php(1545): P\Tests\Feature\Boost\StoreBoostTest->__test()
  #56 /Users/neo/Dev/boosts/vendor/phpunit/phpunit/src/Framework/TestCase.php(1151): PHPUnit\Framework\TestCase->runTest()
  #57 /Users/neo/Dev/boosts/vendor/phpunit/phpunit/src/Framework/TestResult.php(726): PHPUnit\Framework\TestCase->runBare()
  #58 /Users/neo/Dev/boosts/vendor/phpunit/phpunit/src/Framework/TestCase.php(903): PHPUnit\Framework\TestResult->run(Object(P\Tests\Feature\Boost\StoreBoostTest))
  #59 /Users/neo/Dev/boosts/vendor/phpunit/phpunit/src/Framework/TestSuite.php(672): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
  #60 /Users/neo/Dev/boosts/vendor/phpunit/phpunit/src/Framework/TestSuite.php(672): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
  #61 /Users/neo/Dev/boosts/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(673): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
  #62 /Users/neo/Dev/boosts/vendor/phpunit/phpunit/src/TextUI/Command.php(143): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, false)
  #63 /Users/neo/Dev/boosts/vendor/pestphp/pest/src/Console/Command.php(117): PHPUnit\TextUI\Command->run(Array, false)
  #64 /Users/neo/Dev/boosts/vendor/pestphp/pest/bin/pest(62): Pest\Console\Command->run(Array)
  #65 /Users/neo/Dev/boosts/vendor/pestphp/pest/bin/pest(63): {closure}()
  #66 {main}
  
  ----------------------------------------------------------------------------------
  
  Route [login] not defined.

  at tests/Feature/Boost/StoreBoostTest.php:13
      9▕     ->assertRedirectContains('login');
     10▕ 
     11▕ it('will return unauthorized when not logged in again')
     12▕     ->post('/boosts')
  ➜  13▕     ->assertRedirectContains('login');
     14▕ 

  1   [internal]:0
      Illuminate\Testing\TestResponse::assertRedirectContains("login")


  Tests:  1 failed, 1 passed
  Time:   1.79s
```

**Comment by neoighodaro** [comment]
Figured out why

**Comment by gygp-wwa** [comment]
got issues like this when try to test more than 1 http request in same file with same prefix (in my case is /api/v2*).

Second test  url will alway not found
![image](https://github.com/pestphp/pest/assets/167418358/acf09e18-7480-4a76-b88c-2a028bbef9a1)


But when I change url in test2 like this /api/privacy the test will pass fine
![image](https://github.com/pestphp/pest/assets/167418358/a2bbcf1f-d523-4987-a088-dfdf7f31fa3c)


laravel/laravel: 10.48.8 
pestphp/pest: ^2.34
pestphp/pest-plugin-laravel: ^2.3
