### ISSUE TITLE
v2.6.2 Error: Cannot find TestCase object on call stack

### ISSUE THREAD

**Issue by scriptmint** [pestphp/pest#833]
Facing this strange issue in v2.6.2 & v2.6.3 when running tests using --filter. Downgrading to 2.6.1 which uses PHPUnit 10.1.3 fixes the issue. 

This should be related to the PHPUnit repo issue https://github.com/sebastianbergmann/phpunit/issues/5403

There are times (not sure when & why) when a test file having multiple tests throw this error.

**Comment by onlime** [comment]
Thanks @scriptmint for opening this issue. As @sebastianbergmann [mentionend](https://github.com/sebastianbergmann/phpunit/issues/5403#issuecomment-1586020077), this should be solved in PEST. So I am cross-posting my output here:

I am experiencing this bug in a Laravel 10 project with latest PEST v2.6.3 / PHPUnit v10.2.1, e.g.:

```bash
$ php artisan test --filter HasActiveFlagTest

   ERROR  Cannot find TestCase object on call stack

Location: vendor/phpunit/phpunit/src/TextUI/TestRunner.php:68

#0 vendor/phpunit/phpunit/src/TextUI/Application.php(168): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#1 vendor/pestphp/pest/src/Kernel.php(86): PHPUnit\TextUI\Application->run(Array)
#2 vendor/pestphp/pest/bin/pest(91): Pest\Kernel->handle(Array)
#3 vendor/pestphp/pest/bin/pest(99): {closure}()
#4 {main}

Caused by: vendor/phpunit/phpunit/src/Event/Value/Test/TestMethodBuilder.php:62

#0 vendor/phpunit/phpunit/src/Runner/ErrorHandler.php(76): PHPUnit\Event\Code\TestMethodBuilder::fromCallStack()
#1 [internal function]: PHPUnit\Runner\ErrorHandler->__invoke(2, 'preg_match(): D...', '/Users/phi/Site...', 103)
#2 vendor/pestphp/pest/overrides/Runner/Filter/NameFilterIterator.php(103): preg_match('HasActiveFlagTe...', '')
#3 vendor/pestphp/pest/overrides/Runner/Filter/NameFilterIterator.php(69): PHPUnit\Runner\Filter\NameFilterIterator->setFilter('HasActiveFlagTe...')
#4 [internal function]: PHPUnit\Runner\Filter\NameFilterIterator->__construct(Object(PHPUnit\Framework\TestSuiteIterator), 'HasActiveFlagTe...', Object(PHPUnit\Framework\TestSuite))
#5 vendor/phpunit/phpunit/src/Runner/Filter/Factory.php(53): ReflectionClass->newInstance(Object(PHPUnit\Framework\TestSuiteIterator), 'HasActiveFlagTe...', Object(PHPUnit\Framework\TestSuite))
#6 vendor/phpunit/phpunit/src/Framework/TestSuite.php(386): PHPUnit\Runner\Filter\Factory->factory(Object(PHPUnit\Framework\TestSuiteIterator), Object(PHPUnit\Framework\TestSuite))
#7 vendor/phpunit/phpunit/src/Framework/TestSuite.php(272): PHPUnit\Framework\TestSuite->getIterator()
#8 vendor/phpunit/phpunit/src/Framework/TestSuite.php(320): PHPUnit\Framework\TestSuite->count()
#9 vendor/phpunit/phpunit/src/Framework/TestSuite.php(340): PHPUnit\Framework\TestSuite->run()
#10 vendor/phpunit/phpunit/src/Framework/TestSuite.php(340): PHPUnit\Framework\TestSuite->run()
#11 vendor/phpunit/phpunit/src/TextUI/TestRunner.php(63): PHPUnit\Framework\TestSuite->run()
#12 vendor/phpunit/phpunit/src/TextUI/Application.php(168): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#13 vendor/pestphp/pest/src/Kernel.php(86): PHPUnit\TextUI\Application->run(Array)
#14 vendor/pestphp/pest/bin/pest(91): Pest\Kernel->handle(Array)
#15 vendor/pestphp/pest/bin/pest(99): {closure}()
#16 {main}.
```

as a workaround, I had to **downgrade to PHPUnit v10.1.3 / PEST v2.6.1**, and that ERROR no longer pops up.

**Comment by scriptmint** [comment]
Able to reproduce with a fresh Laravel application as below:

composer.json file

```
    "require": {
        "php": "^8.1",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.10",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "pestphp/pest": "^2.6",
        "phpunit/phpunit": "^10.1",
        "spatie/laravel-ignition": "^2.0"
    },
```

Here are the steps to reproduce the issue:

```
laravel new pestphp

cd pestphp

composer require pestphp/pest --dev --with-all-dependencies

./vendor/bin/pest --init
```

Add some tests in Feature/ExampleTest.php

```
<?php

dataset('formData', [
    'default' => [
        [
            'somedata' => 'data',
        ],
    ],
]);

it('is an example', function () {
    $name = 'PestPHP';

    expect($name)->toBeString();
});

it('is another example', function (array $data) {
    expect($data)->toBeArray();
})->with('formData');
```

Running ./vendor/bin/pest doesn't throw any error but running it with filter tag throws error:

```
./vendor/bin/pest --filter="example"
```

```
  ERROR  Cannot find TestCase object on call stack

Location: /Volumes/Coding/Experiment/laravel/pestphp/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:68

#0 /Volumes/Coding/Experiment/laravel/pestphp/vendor/phpunit/phpunit/src/TextUI/Application.php(168): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#1 /Volumes/Coding/Experiment/laravel/pestphp/vendor/pestphp/pest/src/Kernel.php(86): PHPUnit\TextUI\Application->run(Array)
#2 /Volumes/Coding/Experiment/laravel/pestphp/vendor/pestphp/pest/bin/pest(91): Pest\Kernel->handle(Array)
#3 /Volumes/Coding/Experiment/laravel/pestphp/vendor/pestphp/pest/bin/pest(99): {closure}()
#4 /Volumes/Coding/Experiment/laravel/pestphp/vendor/bin/pest(120): include('/Volumes/Coding...')
#5 {main}
```

Downgrading pestphp v2.6.1 works fine!

**Comment by renan-f** [comment]
I'm using version 2.6.3 but the problem still persists

**Comment by mreduar** [comment]
Same problem here v2.6.1 I started experiencing it today after an update.

**Comment by tamimibrahim17** [comment]
It is confirmed that test with **dataset** has this problem. 

No error in this test
```
<?php
it('is an example', function () {
    $name = 'PestPHP';

    expect($name)->toBeString();
});
```
Problematic test
```
<?php

dataset('formData', [
    'default' => [
        [
            'somedata' => 'data',
        ],
    ],
]);

it('is an example', function () {
    $name = 'PestPHP';

    expect($name)->toBeString();
});

it('is another example', function (array $data) {
    expect($data)->toBeArray();
})->with('formData');
```
**Pest version v2.7.0**

**Comment by onlime** [comment]
For me, this problem no longer occurs in **PEST v2.8.0** / PHPUnit 10.2.2

Can anybody or @nunomaduro confirm this? Maybe it's related to [nunomaduro/collision v7.6.0 (2023-06-15)](https://github.com/nunomaduro/collision/compare/v7.5.2...v7.6.0) upgrade. Collision v7.6.0 now supports PHPUnit 10.2.2

**Comment by scriptmint** [comment]
I am still facing the same issue with v2.8.0.

**Comment by nunomaduro** [comment]
Checking...

**Comment by nunomaduro** [comment]
I was able to reproduce it, checking a fix.

**Comment by nunomaduro** [comment]
Fixed on v2.8.1.

**Comment by scriptmint** [comment]
It works. Thanks for your time @nunomaduro!

**Comment by renan-f** [comment]
It worked for me. Thank you very much.

**Comment by rooselle** [comment]
It still didn't work for me. After searching around a bit, I've run following command in a terminal at the root of my project and then it worked: `sudo rm vendor/pestphp/pest/.temp/test-results`
