### ISSUE TITLE
[Bug]: Container exception when use test with Higher Order Testing

### ISSUE THREAD

**Issue by DJafari** [pestphp/pest#941]
### What Happened

check this example :

```php
test('sample', function () {
    get(route('home'))
        ->assertStatus(200);
});
```

now test this :

```php
test('sample 2')
    ->get(route('home'))
    ->assertStatus(200);
```

it's throw to this exception :

```
   ERROR  Target class [url] does not exist.

Location: /vendor/laravel/framework/src/Illuminate/Container/Container.php:914

#0 /vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\Container\Container->build('url')
#1 /vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\Container\Container->resolve('url', Array)
#2 /vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(120): Illuminate\Container\Container->make('url', Array)


```

### How to Reproduce

install a fresh laravel app, add Pest, and test two above example

### Pest Version

2.16.0

### PHP Version

8.2.8

### Operation System

macOS

**Comment by HassanDomeDenea** [comment]
This still not working.
Any solution?
